name: Draft Release

on:
    push:
        branches:
          - main

permissions:
    contents: read

jobs:
    draft-release:
        permissions:
            contents: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
          - uses: release-drafter/release-drafter@v6 # v6.0.0
            with:
                config-name: release-drafter.yaml
                commitish: main
                disable-autolabeler: true
                latest: true
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
