# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Adjust the matrix to test against different or multiple versions.
        # Note that adding more versions will result in a code coverage report 
        # for each version; you may wish to adjust that step's behavior.
        python-version: ["3.11"] 
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5 # actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Ruff check
      run: |
            uvx ruff check
    - name: Install dependencies
      run: |
        uv sync
    - name: Test with pytest
      run: |
        uv run pytest
    - name: Report coverage
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-xml-coverage-path: ./htmlcov/coverage.xml
        title: Coverage report for Python ${{ matrix.python-version }}
        remove-link-from-badge: true
        unique-id-for-comment: ${{ matrix.python-version }}
