# This confirms that the branch name used to open a pull request is valid per the LCAF standards.
# Failing this workflow means that we can't correctly bump versions and deploy.

on:
    pull_request:
        branches: [ "main" ]

name: Validate Branch Name

permissions:
    contents: read

jobs:
    lint:
        name: Validate Branch Name
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Validate Branch Name
              uses: launchbynttdata/actions-lcaf-branch_name@v0
